# Generated by Django 6.0.7 on 2026-07-16 09:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brokerage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BrokerageEndpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.CharField(default='login', max_length=20)),
                ('url', models.URLField()),
                ('http_method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST')], default='POST', max_length=10)),
                ('payload_type', models.CharField(choices=[('JSON', 'application/json'), ('FORM', 'application/x-www-form-urlencoded')], default='JSON', max_length=10)),
                ('default_headers', models.JSONField(blank=True, default=dict)),
                ('success_response_structure', models.JSONField(blank=True, default=dict)),
                ('error_response_structure', models.JSONField(blank=True, default=dict)),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='brokerage.brokerage')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('brokerage', 'purpose'), name='unique_brokerage_endpoint_purpose')],
            },
        ),
        migrations.CreateModel(
            name='UserBrokerageLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_brokerage_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_links', to='brokerage.brokerage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brokerage_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'brokerage'), name='unique_user_brokerage_link')],
            },
        ),
    ]
