# Generated by Django 6.0.7 on 2026-07-13 19:10

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cash_balance', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CashTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('direction', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], max_length=6)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=19)),
                ('resulting_balance', models.DecimalField(decimal_places=4, max_digits=19)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_transactions', to='ledger.portfolio')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['portfolio', 'timestamp'], name='cashtxn_portfolio_ts_idx')],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticker', models.CharField(db_index=True, max_length=10)),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='ledger.portfolio')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('portfolio', 'ticker'), name='unique_portfolio_ticker')],
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ticker', models.CharField(db_index=True, max_length=10)),
                ('trade_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=19)),
                ('price', models.DecimalField(decimal_places=4, max_digits=19)),
                ('total_value', models.DecimalField(decimal_places=4, max_digits=19)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trades', to='ledger.portfolio')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['portfolio', 'timestamp'], name='trade_portfolio_ts_idx')],
            },
        ),
    ]
